name: Delivery

on:
  push:
    branches: [main]

env:
  PYTHON_VERSION: "3.10"

jobs:
  release:
    name: Release new version
    uses: dronetag/gha-shared/.github/workflows/semantic-release.yml@master
    with:
      must-release: true
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Publish Python library to pip
    runs-on: ubuntu-latest
    needs: release
    env:
      RELEASE_TAG: ${{ needs.release.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install the project
        uses: dronetag/gha-shared/.github/actions/poetry-install@master
        with:
          private-pypi-name: dronetag
          private-pypi-host: ${{ secrets.PIP_HOST }}
          private-pypi-user: ${{ secrets.PIP_USER }}
          private-pypi-pass: ${{ secrets.PIP_PASSWORD }}
          python-version: "3.11"
          path: "${{ github.workspace }}/python"
      - name: Run tests
        run: poetry run pytest
      - name: Publish the library
        run: poetry publish --build -r dronetag -n
