name: Delivery

on:
  push:
    branches: [dev]

env:
  PYTHON_VERSION: "3.10"

jobs:
  build:
    name: Publish Python library to pip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '${{ env.PYTHON_VERSION }}'
      - name: Install dependencies
        run: python -m pip install -e .[dev]
      - name: Run tests
        run: pytest
      - name: Build
        run: python -m build --no-isolation
      - name: Publish
        run: |
          python -m twine upload dist/* \
            --repository-url ${{ secrets.PRIV_PIP_HOST }} \
            -u ${{ secrets.PRIV_PIP_USER }} \
            -p ${{ secrets.PRIV_PIP_PASSWORD }}
