name: Pre-release a feature branch (manual)

on:
  workflow_dispatch:

jobs:
  pre-release:
    name: Pre-release new version
    if: startsWith(github.ref, 'refs/heads/feature/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check branch name is "feature/[a-zA-Z\-]
        run: |
          if [[ ! $GITHUB_REF =~ ^refs/heads/feature/[a-zA-Z\-]+$ ]]; then
            echo "Branch name must be feature/[a-zA-Z\-]"
            exit 1
          fi
      - name: Unshallow
        run: |
          git fetch --prune --unshallow --tags
      - name: Create pre-release tag
        run: |
          set -x
          LAST_VERSION=$(git describe --tags --abbrev=0)
          STRIP_VERSION=`echo $LAST_VERSION | sed -n -e 's/^.*v\([0-9\.]*\).*$/\1/p'`
          REF_NAME=`echo $GITHUB_REF | sed -e 's/refs\/heads\///g' | sed -e 's/feature\///g'`
          TAG="$STRIP_VERSION-$REF_NAME.$GITHUB_RUN_NUMBER"
          git config --local user.email ""
          git config --local user.name "GitHub Action"
          git tag $TAG
          git push origin $TAG
