name: "PRE-RELEASE"

on:
  workflow_dispatch:

jobs:
  pre-release:
    name: Pre-release new version
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Get python version
        id: python-version
        run: python --version
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required to determine version
      - name: Check branch name is "feature/[a-zA-Z\-]
        run: |
          if [[ ! $GITHUB_REF_NAME =~ ^feature/[a-zA-Z\-]+$ ]]; then
            echo "Branch name must be feature/[a-zA-Z\-]"
            exit 1
          fi
      - name: Create pre-release tag
        run: |
          LAST_VERSION=$(git describe --tags --abbrev=0)
          echo "Last version: $LAST_VERSION"
          STRIP_VERSION=`echo $LAST_VERSION | sed -n -e 's/^.*\(v[0-9\.]*\).*$/\1/p'`
          echo "Strip version: $STRIP_VERSION"
          if [[ -z "$STRIP_VERSION" ]]; then
            echo "No previous version in format vX.Y.Z found. Consider pruning tags."
            exit 1
          fi
          REF_NAME=`echo $GITHUB_REF_NAME | sed -e 's/feature\///g'`
          echo "Ref name: $REF_NAME"
          TAG="$STRIP_VERSION-$REF_NAME.$GITHUB_RUN_NUMBER"
          echo "Tag: $TAG"
          #git config --local user.email ""
          #git config --local user.name "GitHub Action"
          #git tag -a $TAG -m "pre-release $TAG"
          #git push origin $TAG
