name: 'What is the next version?'

on:
  workflow_dispatch:

jobs:
  release:
    name: Get Next Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository (full-depth)
      uses: actions/checkout@v4
      with: { fetch-depth: 0 } # Required to determine version

    - name: Get next release version
      uses: dronetag/actions/semantic-release@main
      id: semantic
      with:
        changelog: true

    - name: Changelog
      run: echo "${{ steps.semantic.outputs.changelog }}"
