name: "[auto] release-python"

on:
  push:
    tags:
      - "v*"

env:
  PYTHON_VERSION: "3.10"

jobs:
  build:
    name: Release new version to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Check version format vMAJOR.MINOR.PATCH(-SUFFIX)
        run: |
          if [[ ! "$GITHUB_REF_NAME" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+(\.[a-zA-Z0-9]+)*)?$ ]]; then
            echo "Invalid version format. Expected vMAJOR.MINOR.PATCH(-SUFFIX)?, got ${GITHUB_REF_NAME}"
            exit 1
          fi
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install the project
        uses: dronetag/gha-shared/.github/actions/poetry-install@master
        with:
          private-pypi-name: dronetag
          private-pypi-host: ${{ secrets.PRIV_PIP_HOST }}
          private-pypi-user: ${{ secrets.PRIV_PIP_USER }}
          private-pypi-pass: ${{ secrets.PRIV_PIP_PASSWORD }}
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Poetry update version
        run: |
          poetry version "${GITHUB_REF_NAME#v}"
          poetry publish --build -n -r dronetag

      - name: Commit version on release branch
        run: |
          if [[ $(git rev-parse heads/main) = $(git rev-parse ${GITHUB_REF}) ]]; then
            echo "We are at the top of main branch so we can commit the version bump"
            git checkout main
            git add pyproject.toml
            git commit -m "Release ${GITHUB_REF_NAME#v} [skip ci]"
            git push
          fi
