name: Release main branch (manual)

on:
  workflow_dispatch:

jobs:
  release:
    name: Release new version
    if: github.ref == 'refs/heads/main'
    uses: dronetag/gha-shared/.github/workflows/semantic-release.yml@master
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
