name: Release

on:
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.10"

jobs:
  build:
    name: Release new version to PyPI
    runs-on: ubuntu-latest
    needs: release
    env:
      RELEASE_TAG: ${{ needs.release.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install the project
        uses: dronetag/gha-shared/.github/actions/poetry-install@master
        with:
          private-pypi-name: dronetag
          private-pypi-host: ${{ secrets.PRIV_PIP_HOST }}
          private-pypi-user: ${{ secrets.PRIV_PIP_USER }}
          private-pypi-pass: ${{ secrets.PRIV_PIP_PASSWORD }}
          python-version: "${{ env.PYTHON_VERSION }}"
      - name: Bump version
        run: poetry version $(RELEASE_TAG)
      - name: Publish
        run: poetry publish --build -n -r dronetag

  release:
    name: Release new version
    uses: dronetag/gha-shared/.github/workflows/semantic-release.yml@master
    with:
      must-release: true
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}