name: Release on PYPI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*

env:
  PYTHON_VERSION: "3.10"

jobs:
  build:
    name: Release new version to PyPI
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: ${{ env.GITHUB_REF }}  # v1.0.0 -> 1.0.0 we need to remove the prefix "v"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install the project
        uses: dronetag/gha-shared/.github/actions/poetry-install@master
        with:
          private-pypi-name: dronetag
          private-pypi-host: ${{ secrets.PRIV_PIP_HOST }}
          private-pypi-user: ${{ secrets.PRIV_PIP_USER }}
          private-pypi-pass: ${{ secrets.PRIV_PIP_PASSWORD }}
          python-version: "${{ env.PYTHON_VERSION }}"
      - name: Bump version
        run: poetry version ${RELEASE_VERSION:1}
      - name: Commit and push
        run: |
          git config --local user.email "" # Set empty email
          git config --local user.name "GitHub Action"
          git add pyproject.toml
          git commit -m "chore(ci): bump pyproject.toml version to ${RELEASE_VERSION:1}"
          git push
      - name: Publish
        run: poetry publish --build -n -r dronetag
