name: Test (automatic)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: "3.10"

jobs:
  build:
    name: Run automated tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install the project
        uses: dronetag/gha-shared/.github/actions/poetry-install@master
        with:
          python-version: "${{ env.PYTHON_VERSION }}"
      - name: Install DEV dependencies
        run: poetry install -E dev
      - name: Run pro-commit checks
        run: poetry run pre-commit run --all-files
      - name: Run tests
        run: poetry run pytest

      - name: Run coverage test
        run: poetry run pytest --cov=mavsniff > ./pytest-coverage.txt
      - name: Create coverage comment (great for examining pull-requests)
        id: coverage
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
      # only on main branch
      - name: Create the Badge
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_UPDATE_TOKEN }}
          gistID: bda1e64c276a6d6e6a4e65fb5dc9330b
          filename: coverage.json
          label: Test coverage
          message: ${{ steps.coverage.outputs.coverage }}
          color: ${{ steps.coverage.outputs.color }}
          namedLogo: python
