name: Delivery

on:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: "3.10"

jobs:
  build:
    name: Run automated tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install the project
        uses: dronetag/gha-shared/.github/actions/poetry-install@master
        with:
          python-version: "${{ env.PYTHON_VERSION }}"
      - name: Install DEV dependencies
        run: poetry install -E dev
      - name: Run tests
        run: poetry run pytest
